# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/localhost/all/localhost.rbi
#
# localhost-1.1.9

module Localhost
end
class Localhost::Authority
  def certificate; end
  def certificate_path; end
  def client_context(*args); end
  def dh_key; end
  def ecdh_key; end
  def hostname; end
  def initialize(hostname = nil, root: nil); end
  def key; end
  def key=(key); end
  def key_path; end
  def load(path = nil); end
  def name; end
  def name=(name); end
  def save(path = nil); end
  def self.fetch(*arguments, **options); end
  def self.list(root = nil); end
  def self.path; end
  def server_context(*arguments); end
  def store; end
end
