# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mapping/all/mapping.rbi
#
# mapping-1.1.1

module Mapping
end
class Mapping::Model
  def map(root, *args); end
  def method_for_mapping(object); end
  def self.map(*klasses, &block); end
  def self.map_identity(*klasses); end
  def self.method_for_mapping(klass); end
  def self.unmap(*klasses); end
end
