# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `prettier` gem.
# Please instead update this file by running `bin/tapioca gem prettier`.

# source://prettier-3.2.0/lib/prettier.rb:6
module Prettier
  class << self
    # source://prettier-3.2.0/lib/prettier.rb:11
    def run(args); end
  end
end

# source://prettier-3.2.0/lib/prettier.rb:8
Prettier::BINARY = T.let(T.unsafe(nil), String)

# source://prettier-3.2.0/lib/prettier.rb:7
Prettier::PLUGIN = T.let(T.unsafe(nil), String)

# source://prettier-3.2.0/lib/prettier.rb:9
Prettier::VERSION = T.let(T.unsafe(nil), String)
