# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rux/all/rux.rbi
#
# rux-1.0.3

module Rux
  def self.buffer; end
  def self.buffer=(arg0); end
  def self.create_buffer; end
  def self.default_buffer; end
  def self.default_tag_builder; end
  def self.default_visitor; end
  def self.library_paths; end
  def self.tag(tag_name, attributes = nil, &block); end
  def self.tag_builder; end
  def self.tag_builder=(arg0); end
  def self.to_ruby(str, visitor: nil, pretty: nil); end
end
class Rux::DefaultTagBuilder
  def call(tag_name, attributes = nil); end
  def serialize_attrs(attributes); end
end
class Rux::Buffer
  def <<(*obj); end
  def initialize(init_str = nil); end
  def to_s; end
end
