[development]
  secret_key = "dev"

  [development.server]
    listen = "https://localhost:9393"

    hmr = true

    render_exceptions = true
    self_signed_cert = true

    generate_assets = true

    session_timeout_seconds = 15
    transfer_timeout_seconds = 10

  [development.metrics]
    enabled = true

[production]
  secret_key = "$MAYU_SECRET_KEY"

  [production.server]
    # listen = "https://0.0.0.0:3333"
    listen = "https://localhost:3333"

    hmr = false

    render_exceptions = false
    self_signed_cert = true

    generate_assets = false

  [production.metrics]
    enabled = true
    port = 9091
    host = "0.0.0.0"
