[dev]
  secret_key = "dev"

  [dev.server]
    listen = "https://localhost:9393"

    hmr = true

    render_exceptions = true
    self_signed_cert = true

    generate_assets = true

  [dev.metrics]
    enabled = true

[prod]
  secret_key = "prod"

  [prod.server]
    listen = "http://0.0.0.0:3000"

    hmr = false

    render_exceptions = false
    self_signed_cert = false

    generate_assets = false

  [prod.metrics]
    enabled = true
    port = 9091
    host = "0.0.0.0"
