[dev]
  # These settings don't do anything.. yet
  port = 9292
  hot_reload = true

[prod]
  hostname = "mayu.live"
  port = 3000
  num_processes = 1
  max_sessions = 4
  keepalive_seconds = 10
  print_capacity_interval = 5
  heartbeat_interval = 0.5
