demos = "Demos"
i18n = "Translations"
pokemon = "Pokémon"
tree = "App tree"
form = "Form elements"
images = "Images"
svg = "Scalable Vector Graphics"
fuzzymatch = "Fuzzy matcher"
todo = "Todo app"
life = "Game of life"
events = "Events"
exceptions = "Exceptions"
