[en]
demos = "Demos"
i18n = "Translations"
pokemon = "Pokémon"
tree = "App tree"
form = "Form elements"
images = "Images"
svg = "Scalable Vector Graphics"
fuzzymatch = "Fuzzy matcher"
todo = "Todo app"
life = "Game of life"
events = "Events"
exceptions = "Exceptions"

[sv]
demos = "Demos"
i18n = "Översättningar"
pokemon = "Pokémon"
tree = "Applikationsträd"
form = "Formulärelement"
images = "Bilder"
svg = "Scalable Vector Graphics"
fuzzymatch = "Fuzzymatchning"
todo = "Att göra-app"
life = "Livets spel (Game of life)"
events = "Händelser"
exceptions = "Exceptions"
