[base]
  hot_reload = false
  secret_key = "asd"

[env.dev]
  port = 9292
  host = "localhost"
  hot_reload = true

[env.prod]
  host = "0.0.0.0"
  port = 3000
  num_processes = 4
  max_sessions = 10
