what_needs_to_be_done = "What needs to be done?"
clear_completed = "Clear completed"

[item]
  one = "%<count>d item left"
  many = "%<count>d items left"

[filter]
  all = "All"
  active = "Active"
  completed = "Completed"
