#!/usr/bin/env ruby

MAYU_ROOT = File.join(File.dirname(__FILE__), "..")
$LOAD_PATH.unshift(File.join(MAYU_ROOT, "..", "..", "lib"))

require "mayu/banner"

COMMANDS = {
  "dev" => -> do
    exec("bundle", "exec", "falcon", "serve", "--threaded", "--count", "2")
  end,
  "prod" => -> { exec("bundle", "exec", "falcon", "host") }
}

cmd, *rest = ARGV

$stderr.puts "\e[36m#{Mayu::BANNER}\e[0m"

COMMANDS
  .fetch(cmd) do
    if cmd
      $stderr.puts "Unknown command: #{cmd}"
    else
      $stderr.puts "Missing command argument!"
    end

    $stderr.puts
    $stderr.puts "Try any of the following:"

    COMMANDS.keys.each { |cmd| puts "\t#{$0} #{cmd}" }

    exit 1
  end
  .call(*rest)
