#!/usr/bin/env ruby

MAYU_ROOT = File.join(File.dirname(__FILE__), "..")
$LOAD_PATH.unshift(File.join(MAYU_ROOT, "..", "..", "lib"))

if RubyVM.const_defined?(:YJIT)
  if RubyVM::YJIT.enabled?
    puts "\e[1mYJIT is enabled!\e[0m"
  else
    puts "\e[2mYJIT is disabled!\e[0m"
  end
else
  puts "\e[2mYJIT is not supported!\e[0m"
end

require "mayu/version"
require "mayu/commands"

Mayu::Commands.call(ARGV)
