# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module Rack::QueryParser::InvalidParameterError; end
module Rack::QueryParser::ParameterTypeError; end
module Rack::QueryParser::Params; end
